dcloudio/uni-app

packages/webpack-uni-mp-loader/lib/main-new.js
packages/webpack-uni-mp-loader/lib/script-new.js

`typescript`已经支持` ?. `了。为了统一，让`.vue`里的`script`也支持 `optionalChaining`
`babel.config.js` 自行添加 `@babel/plugin-proposal-optional-chaining`

add optionalChaining

---

src/platforms/h5/service/api/media/choose-video.js

默认video.onloadedmetadata的值是null，是为false;判断video是否支持onloadedmetadata方法应该判断是否是undefined

修复video onloadedmetadata判断问题

---

src/core/view/components/image/index.vue

使用 image 组件时，如果图片的 url 里带有英文括号，就无法展示图片，原因是设置 backgroundImage 样式的时候没有为 url 里的字符串添加引号，导致 url 与样式的括号冲突
现在稍微修改，加上双引号了

优化 image 组件

---

packages/uni-template-compiler/lib/auto-components.js

fix #1351 
造成 app.json 被覆盖的原因是先生成了正常的 app.json 然后(Windows 下)又被不应该存在的 App.json 覆盖掉了，应去掉 App.json 的生成。

修复 app.json 生成后被部分覆盖的问题

---

packages/uni-cli-shared/lib/manifest.js

h5.router.base 增加相对路径支持
要在 build 支持相对路径时
只需要配置 manifest `h5.router.base` 为 `'./'`, 配置 `h5.publicPath` 为 `'./'` 或留空不配置
这样 h5 就支持部署在任意路径下
例如，将生成的包放在 www/abcd/ 下，用 nginx 启动 www 目录，则可以通过 /abcd/ 来访问网站。不需要在代码中配置 abcd
优化了 `indexOf`/`substr` 的写法，使用 `startsWith`/`endsWith` 更加语义化
关联 issue #1389 #571

feat: h5.router.base 增加相对路径支持

---

packages/webpack-uni-pages-loader/lib/platforms/mp-weixin/project.config.json

取消固定微信小程序调试基础库版本

---

docs/resource.md

原链接：https://ke.qq.com/course/2409672?taid=8858395820213448&tuin=258d8def
因为腾讯课堂限制了，课程报名时间。导致现在新用户要看课程都报名不了。
现在已经将课程上传到网易云课堂；新链接：
https://study.163.com/course/introduction.htm?courseId=1209978085#/courseDetail?tab=1
请帮忙更换一下

因为腾讯课堂限制了，课程报名时间。导致现在新用户要看课程都报名不了

---

packages/vue-cli-plugin-uni/lib/split-chunks.js

Fix split module from main package component in sub-packages optimization

---

src/core/view/components/image/index.vue

https://github.com/dcloudio/uni-app/blob/9fa8d6953058226b7ccf7745f4c6c2a58fedc2c7/src/core/view/components/image/index.vue#L7
新增判断contentPath有值再渲染img
```html
<img
v-if="contentPath"
:src="contentPath"
>
```

fix: 修复 image 组件 contentPath 字段默认为空导致 img 请求空问题

---

packages/vue-cli-plugin-uni/lib/split-chunks.js

在分包代码优化过程中，进一步解决第三组件间接引用的js module被拆分到子包中。
Fixes #2196

fix split indirect refer js module into subpackage when split chunks

---

docs/component/swiper.md

1. 在监听`animationfinish`事件时如果不监听`change`事件，则返回的 `event.detail`始终为第一次的数据

docs: 增加swiper `animationfinish`事件返回错误数据说明

---

packages/webpack-uni-mp-loader/lib/plugin/generate-json.js

一个小 bug，Set 没有 length 方法，这里逻辑永远为 false。
因此当 component 被多个分包引用时这里不会返回，导致控制台依然会产生建议移动到子包的提示：
```
A B 为分包，X 为公共组件，且未被主包引用
仍然提示：自定义组件 X 建议移动到子包 A 内
```
修复后可消除提示

fix: 修复多分包共用组件仍然提示建议移动的问题

---

packages/vue-cli-plugin-uni/packages/app-vue-style-loader/lib/addStylesClient.js
packages/vue-cli-plugin-uni/packages/h5-vue-style-loader/lib/addStylesClient.js

相关issue: [2600](https://github.com/dcloudio/uni-app/issues/2600)
```
css.replace(/\{[\s\S]+?\}|@media[^{]+/g, function (css) {
return css.replace(UPX_RE, function (a, b) {
return uni.upx2px(b) + 'px'
})
})
```
@media部分应该是想处理类似这样的情形：
```
@media screen and (max-width: 300rpx)
```
####以上代码在兼容该情形的基础上，处理了以下特殊情况：
```
.comp-card .header--wrap .line[data-v-8ec74a42] {
position: absolute;
bottom: 0;
left: %?24?%;
width: %?678?%;
height: 1px;
background: #f7f7f7;
}
@media only screen and (-webkit-min-device-pixel-ratio: 2) {
.comp-card .header--wrap .line[data-v-8ec74a42] {
-webkit-transform: scaleY(0.5);
-ms-transform: scaleY(0.5);
transform: scaleY(0.5);
}
}
.comp-card .content--wrap[data-v-8ec74a42] {
padding: %?22?% %?24?%;
}
```

fix(H5): 修复h5端部分rpx单位没有转化为px的问题

---

packages/vue-cli-plugin-uni/lib/util.js

Fixes #2760.
解决yarn link和npm link时候，uniapp工程不会自动触发编译问题。

remove watch options: ignore node_modules.

---

packages/webpack-uni-mp-loader/lib/plugin/index-new.js

修复：支付宝小程序报错：Module not found: Error: Can't resolve 'common/vendor.js'
支付宝require 无法将 common/vendor.js 识别为 ./common/vendor.js。
详见issue：https://github.com/dcloudio/uni-app/issues/3059

fix(webpack-uni-app-loader): 部分平台无法识别不以 . 开头的相对路径

---

packages/uni-cli-shared/lib/package.js

如果有package.json下的uni-app->scripts配置有两个平台以上且有相同的自定义编译条件变量时会导致变量覆盖为false

fix:修正package.json配置自定义编译条件覆盖为false

---

packages/uni-cli-shared/lib/package.js

如果有package.json下的uni-app->scripts配置有两个平台以上且有相同的自定义编译条件变量时且非当前运行平台会导致变量覆盖为true

fix:修正package.json配置自定义编译条件覆盖为true

---

packages/webpack-uni-mp-loader/lib/plugin/index-new.js

支付宝小程序修改前编译 main.js 结果：
修改后：
支付宝小程序插件，默认编译报错，需要单独导出和外部通信的文件。
微信小程序不受本次代码的影响，微信端的编译和修改后的一致。
示例项目：https://github.com/Yaob1990/uni-plugin-template

fix(小程序插件): 小程序插件 main.js 文件中导出的函数位置调整

---

packages/vue-cli-plugin-uni/lib/configure-webpack.js

当前仅有 微信小程序的代码 在开发阶段会以 sourceMap 文件的形式构建，其他小程序平台基本都是 inline-source-map 的形式。
由于头条小程序开发的时候，转译体积明显比 微信的小程序产物要大，因此同一份代码在微信开发者工具中能够正常上传，在头条小程序开发者工具中就不能上传了。
所以增加对 头条小程序 的支持，使得 sourcMap 产物也是 文件形式，而不是内联的。
> 进一步可以考虑对所有平台使用同样的策略，待讨论。

feat: 支持头条小程序在开发阶段使用 sourceMap file 形式

---

src/platforms/h5/helpers/get-jsonp.js

[#3681](https://github.com/dcloudio/uni-app/issues/3681)

fix: 解决同一时刻发送多个jsonp请求，仅有一个请求会正常执行callback的问题

---

src/platforms/mp-alipay/runtime/wrapper/util.js

项目编译成支付宝小程序插件，页面内的子组件使用ref会报错
#2974

支付宝小程序组件中使用ref报错

---

src/platforms/mp-alipay/runtime/wrapper/util.js
src/platforms/mp-xhs/runtime/wrapper/util.js

使用插件提供的组件时，如果没有给插件中的组件添加事件，最终的编译产物里面会因为缺少`data-event-list`属性而导致插件运行时报错
复现demo：https://github.com/EAGzzyCSL/my-uni-app-demo/commit/29529c576b8ad00c560612fb080faf4a49f6773e
```html
<template>
<view class="content">
<image class="logo" src="/static/logo.png"></image>
<view>
<text class="title">{{title}}</text>
<ad-list resourceId="AD_20211201000000101279" />
</view>
</view>
</template>
```
```html
<view class="content">
<image class="logo" src="/static/logo.png"></image>
<view>
<text class="title">{{title}}</text>
<plugin-wrapper vue-id="8deb4120-1" onPluginWrap="__w" data-com-type="wx" onVueInit="__l" vue-slots="{{['default']}}">
<ad-list resourceId="AD_20211201000000101279" onVueInit="__l"></ad-list>
</plugin-wrapper>
</view>
</view>
```
```html
<template>
<view class="content">
<image …
```

兜底data-event-list 属性为 undefined 的情况

---

packages/uni-h5/src/framework/setup/index.ts

有的老版本浏览器只有MediaQueryList.addListener方法，没有addEventListener方法。
需做兼容处理。

fix(h5):mediaQueryList.addEventListener undefined

---

lib/h5/uni.config.js

copyWebpackPlugin的[ext]包含dot是从v8后开始的，可见下面的changelog，我这边测试v6.4.1版本[ext]还是不包含dot的，会出现uni-h5的css文件没后缀的情况:
https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/CHANGELOG.md#-breaking-changes-3

fix(h5): wrong version check for copyWebpackPlugin

---

src/platforms/app-plus/view/framework/plugins/vdom-sync.js

报错信息:
```bash
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```
在`initVm`初始化时, updateBatchVData根据_$id查询时如果不存在, 给的是 `vData = { data: {}, options: {} }`
但在`addVData`, 和`updateVData`调用时是给的`[data, options]`
所以 调用 `_slicedToArray(vData)`方法时, 报迭代错误.

fix: 补丁默认数据类型错误

---

src/platforms/h5/components/app/popup/toast.vue

fix(H5): 调整uni.showToast提示文本自动换行的处理方法

---

packages/uni-mp-compiler/__tests__/slot.spec.ts
packages/uni-mp-compiler/src/template/codegen.ts

原本 `<slot name='text-name'>占位符</slot>` 会编译成
```js
<block wx:if="{{$slots.text-name}}">
<slot name="text-name"></slot>
</block>
<block wx:else>Submit</block>
```
js 对象的属性中，访问带横线的属性，不能通过 `.` 直接访问，需要使用 `['a-b']` 包裹
这里对这种异常情况进行兼容，补充了对应的单元测试

feat(uni-mp-compiler): 对具名插槽 name 包含短横线的边缘情况进行处理

---

packages/uni-template-compiler/lib/mp.js

fix(mp-weixin): 回退微信小程序对 span 的忽略处理

---

packages/uni-components/src/helpers/useField.ts
packages/uni-components/src/vue/input/index.tsx

fix: 修复IOS16及以上连续输入小数点自动删除数字的bug

---

packages/uni-components/src/vue/resize-sensor/index.tsx
pnpm-lock.yaml

https://github.com/dcloudio/uni-app/issues/4874

fix(uni-components): 修复ResizeSensor组件rootRef.value可能为空的bug (close #4874)

---

packages/vite-plugin-uni/src/vue/options.ts

目前不支持用户传递  templateOptions.transformAssetUrls.tags 导致
``` html
<template>
<div>
<image :src="src"  mode="scaleToFill" />
</div>
</template>
<script lang="ts" setup>
defineProps<{
src: string;
}>();
</script>
```
这种自定义组件无法传递 props.src 参数

支持自定义 template.transformAssetUrls

---

packages/vue-cli-plugin-uni/lib/mp/index.js

fix(mp): 去除 mini-css-extract-plugin 的 css runtime

---

packages/uni-mp-kuaishou/src/compiler/options.ts

起因是使用快手小程序插件开发短剧功能 （[插件文档](https://open.kuaishou.com/docs/develop/functionAccessGuide/playletplugin.html)）,发现bindplay和bindpause相关事件无法触发，我看源码中（[文件](https://github.com/dcloudio/uni-app/blob/next/packages/uni-mp-kuaishou/src/compiler/transforms/vOn.ts)）说快手小程序的自定义组件，不支持动态事件绑定。所以建议先把playlet-plugin声明为内部组件来处理。
其次，快手1.99.3开始支持动态事件了，建议官方大佬可以重新调整一下这部分的逻辑了，感谢🙏。

fix(mp): 支持快手的插件事件

---

packages/uni-components/src/helpers/useField.ts

[https://ask.dcloud.net.cn/question/207894](https://ask.dcloud.net.cn/question/207894)
[https://ask.dcloud.net.cn/question/183911](https://ask.dcloud.net.cn/question/183911)
[https://ask.dcloud.net.cn/question/163899](https://ask.dcloud.net.cn/question/163899)
```vue
<template>  
<view>  
<view> val: {{ val }}  </view>
<textarea inputmode="none" :focus="true" style="border: 1px solid red" />  
</view>  
</template>  
<script lang="ts" setup>  
import { ref } from 'vue';  
const val = ref();  
</script>
```
https://github.com/user-attachments/assets/755c7e93-0177-4685-9f86-374e311046a5
https://github.com/user-attachments/assets/e876f914-8713-49b3-8166-e121ebfde8ed

fix(app): inputmode为none时，设置focus为true能弹起键盘的bug (question/207894)

---

src/core/view/mixins/field.js

```vue
<template>
<view class="content">
<image class="logo" src="/static/logo.png"></image>
<view class="text-area">
<text class="title">{{title}}</text>
</view>
<textarea inputmode="none" :focus="true" style="border: 1px solid red" />
</view>
</template>
<script>
export default {
data() {
return {
title: 'Hello'
}
},
onLoad() {
},
methods: {
}
}
</script>
```
https://github.com/user-attachments/assets/adb00a75-4853-406e-9545-4dbd3eab7108
https://github.com/user-attachments/assets/9c8420e6-6912-4787-9126-75c88c813769

fix(app): inputmode为none时，设置focus为true弹起键盘的bug (question/207894)

---

packages/uni-h5/src/framework/setup/index.ts

[https://ask.dcloud.net.cn/question/139069](https://ask.dcloud.net.cn/question/139069)
```vue
<template>
<view class="content">
<image class="logo" src="/static/logo.png"></image>
<view class="text-area">
<text class="title">{{title}}</text>
</view>
</view>
</template>
<script>
export default {
data() {
return {
title: ''
}
},
onLoad() {
const config = uni.getSystemInfoSync();
this.title = `windowTop:${config.windowTop}`
},
methods: {
}
}
</script>
```

fix(web): 修复uni.getSystemInfoSync().windowTop计算的值不正确 (question/139069)

---

packages/uni-h5/style/api/toast.css

[https://ask.dcloud.net.cn/question/209029?item_id=297992&rf=false](https://ask.dcloud.net.cn/question/209029?item_id=297992&rf=false)

fix(web): 修复showToast中title为英文短句时单词拆分的问题 (question/297992)

---

packages/uni-mp-kuaishou/src/compiler/options.ts

[#5280 ](https://github.com/dcloudio/uni-app/issues/5280) 快手小程序已经支持动态插槽名了，所以可以把编译选项打开。

fix(mp): 支持快手的动态插槽名

---

packages/uni-mp-kuaishou/__tests__/vModel.spec.ts
packages/uni-mp-kuaishou/__tests__/vOn.spec.ts
packages/uni-mp-kuaishou/src/compiler/options.ts

#5332 支持快手小程序动态事件
快手小程序已经的微信对齐了组件事件相关功能，因此不需要对快手平台额外去处理组件事件。

支持快手小程序动态事件

---

src/core/view/components/button/index.vue
src/core/view/components/checkbox/index.vue
src/core/view/components/radio/index.vue
src/core/view/components/switch/index.vue

```vue
<template>
<view>
<button id="button">DIY可视化</button>
<switch id="switch" color="#FFCC33" style="transform:scale(0.7)" />
<radio id="radio" value="r2" />未选中
<checkbox id="checkbox" value="cb" checked="true" />选中
</view>
</template>
<script>
export default {
mounted() {
const view = uni.createSelectorQuery().in(this).select('#button')
view
.boundingClientRect((data) => {
console.log("button 得到布局位置信息", data);
})
.exec();
const view1 = uni.createSelectorQuery().in(this).select('#switch')
view1
.boundingClientRect((data) => {
console.log("switch 得到布局位置信息", data);
})
.exec();
const view2 = uni.createSelectorQuery().in(this).select('#radio')
view2
.boundingClientRect((data) => {
console.log("radio 得到布局位置信息", data);
})
.exec();
const view3 = …
```

 fix(components): 修复部分内置组件id属性无效的问题 (question/170515)

---

packages/uni-mp-alipay/__tests__/vOn.spec.ts
packages/uni-mp-alipay/src/compiler/event.ts

close #4339 
[https://ask.dcloud.net.cn/question/209386](https://ask.dcloud.net.cn/question/209386)

fix(mp-alipay): 支持捕获事件修饰符 .capture (question/209386)

---

packages/uni-h5/src/service/api/media/previewImage/ImagePreview.tsx

[https://ask.dcloud.net.cn/question/209551](https://ask.dcloud.net.cn/question/209551) 
https://github.com/user-attachments/assets/602c800c-dae7-4b13-bc51-233b58e4b340

feat(web): previewImage 支持点击 esc 关闭预览 (question/209551)

---

packages/uni-mp-compiler/__tests__/hidden.spec.ts
packages/uni-mp-compiler/src/transforms/transformHidden.ts

[https://ask.dcloud.net.cn/question/204902](https://ask.dcloud.net.cn/question/204902)

fix(mp): 修复小程序 hidden 属性通过 v-bind 绑定变量失效的bug (question/204902)

---

packages/uni-mp-compiler/src/template/codegen.ts

[https://ask.dcloud.net.cn/question/60628](https://ask.dcloud.net.cn/question/60628)

fix(mp): 修复小程序端 &lt; 和 &gt; 编译为 < 和 > 导致运行报错的bug (question/60628)

---

packages/uni-components/src/vue/textarea/index.tsx
packages/uni-components/style/textarea.css

[https://ask.dcloud.net.cn/question/173645](https://ask.dcloud.net.cn/question/173645)
1.0 的 app和web端，2.0 的 web 端
```vue
<template>
<textarea
placeholder="请输入"
auto-height
style="width: 100px; border: 1px solid red"
/>
</template>
```

fix(textarea): 修复全输入符号设置 auto-height 属性不会自动增加高度的bug (question/173645)

---

packages/uni-mp-toutiao/src/compiler/options.ts

[https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/dev-tools/developer-instrument/development-assistance/private-config](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/dev-tools/developer-instrument/development-assistance/private-config)

feat(mp-toutiao): 支持拷贝 project.private.config.json 到产物根目录

---

packages/uni-mp-compiler/__tests__/scopedSlot.spec.ts
packages/uni-mp-compiler/__tests__/slot.fallback.spec.ts
packages/uni-mp-compiler/__tests__/slot.spec.ts
packages/uni-mp-compiler/src/template/codegen.ts
packages/uni-mp-compiler/src/transforms/transformSlot.ts

```vue
// index.vue
<template>
<view>
<test> hello </test>
</view>
</template>
<script setup>
import test from "./test.vue";
</script>
```
```vue
<template>
<view>
<slot :subTitle="subTitle">ddd</slot>
</view>
</template>
<script setup>
import { ref } from 'vue'
const subTitle =  ref('test');
</script>
```

fix(mp): 修复子组件 slot 有默认内容和 props 时父组件默认插槽不生效的bug

---

packages/uni-h5/style/api/modal.css

fix(web): 修复 showModal 设置 editable 为 true 时单行中文内容出现滚动条的问题

---

packages/uni-mp-alipay/__tests__/vSlot.spec.ts
packages/uni-mp-baidu/__tests__/vSlot.spec.ts
packages/uni-mp-compiler/__tests__/vFor.spec.ts
packages/uni-mp-compiler/__tests__/vSlot.spec.ts
packages/uni-mp-compiler/src/transforms/vSlot.ts

[https://ask.dcloud.net.cn/question/210538](https://ask.dcloud.net.cn/question/210538)
```vue
<template>
<view>
<Test>
<template #header></template>
<template></template>
<template v-slot:footer> </template>
<template v-slot:a="{ a }"></template>
<template #left>left</template>
<template v-slot:right="{ }">right</template>
</Test>
</view>
</template>
```
```vue
<view class="{{[virtualHostClass]}}" style="{{virtualHostStyle}}" hidden="{{virtualHostHidden || false}}" id="{{c}}">
<test u-s="{{['left','right']}}" u-i="bf84929c-0" bind:__l="__l">
<view slot="left">left</view>
<view wx:for="{{b}}" wx:for-item="v0" wx:key="a" slot="{{v0.b}}">right</view>
</test>
</view>
```

fix(mp): 修复插槽默认内容编译不生效的bug (question/210538)

---

packages/uni-mp-compiler/__tests__/mergeVirtualHostAttributes.spec.ts
packages/uni-mp-compiler/src/transforms/transformHidden.ts

mainfest.json 中设置  "mergeVirtualHostAttributes" : true
```vue
<template>
<view :hidden="show">
hello uniapp
</view>
</template>
<script>
export default {
data() {
return {
show: true
}
}
}
</script>
```

fix(mp): 修复根节点设置 v-show 或 hidden 失效的bug

---

packages/uni-cli-shared/src/env/define.ts
packages/uni-cli-shared/src/vite/plugins/vitejs/plugins/asset.ts
packages/uni-cli-shared/src/vite/plugins/vitejs/plugins/static.ts

[https://ask.dcloud.net.cn/question/194903](https://ask.dcloud.net.cn/question/194903)

fix(mp): 修复多个子包引用相同图片时 Vite 默认优化导致路径被合并的问题 (question/194903)

---

packages/uni-mp-alipay/src/compiler/options.ts

[https://opendocs.alipay.com/mini/framework/app-json#window](https://opendocs.alipay.com/mini/framework/app-json#window)

fix(mp-alipay): 修复 globalStyle 中设置 navigationBarTextStyle 不生效的Bug

---

packages/uni-template-compiler/__tests__/compiler-extra.spec.js
packages/uni-template-compiler/lib/script/traverse/data/class.js

close #3101 
```vue
<view :class="{ [test]: true }">Hello {{ test }}</view>
```
```js
<view class="{{[(true)?'test':'']}}">{{"Hello "+test}}</view>
```
```js
<view class="{{[(true)?test:'']}}">{{"Hello "+test}}</view>
```

fix(mp): 修复类名为变量时未能正确编译的Bug

---

packages/uni-mp-xhs/src/api/protocols.ts

[https://miniapp.xiaohongshu.com/doc/DC411188](https://miniapp.xiaohongshu.com/doc/DC411188)

fix(mp-xhs): 修复 API requestPayment 调用不生效的 Bug (question/194812)

---

packages/uni-mp-compiler/__tests__/wxs.spec.ts
packages/uni-mp-compiler/src/transforms/transformClass.ts

```vue
<template>
<view class="page">
<view :class="utils.cls('l-checkbox', [
['checked', true]
])">
<text>{{utils.cls('l-checkbox', [
['checked', true]
])}}</text>
</view>
</view>
</template>
<script lang="wxs" src="./utils.wxs" module="utils"></script>
<style lang="scss">
.l-checkbox {
background-color: red;
height: 500px;
width: 500px;
}
</style>
```
```js
function cls(base, arr) {
var res = [base];
var i = 0;
for (var size = arr.length; i < size; i++) {
var item = arr[i];
if (item && item.constructor === 'Array') {
var key = arr[i][0];
var value = arr[i][1];
if (value) {
res.push(base + '--' + key);
}
} else if (typeof item === 'string' || typeof item === 'number') {
if (item) {
res.push(base + '--' + item);
}
}
}
return res.join(' ');
}
module.exports = {
cls: cls
};
```
样式没生效

fix(mp): 修复 wxs 中动态绑定 class 不生效的Bug

---

packages/uni-mp-vite/src/plugin/build.ts

[https://opendocs.alipay.com/mini/plugin/plugin-usage#%E5%AF%BC%E5%87%BA%E5%88%B0%E6%8F%92%E4%BB%B6](https://opendocs.alipay.com/mini/plugin/plugin-usage#%E5%AF%BC%E5%87%BA%E5%88%B0%E6%8F%92%E4%BB%B6)

fix(mp-alipay): 修复 plugins export 字段不生效的 Bug

---

packages/uni-mp-baidu/src/api/protocols.ts

百度小程序官方文档 [https://smartprogram.baidu.com/docs/develop/api/open/swan-navigateToSmartProgram/](https://smartprogram.baidu.com/docs/develop/api/open/swan-navigateToSmartProgram/)

fix(mp-baidu): 修复 API navigateToMiniProgram 提示不支持 envVersion 的 Bug
