dcloudio/uni-app

src/core/view/components/movable-view/index.vue
=> fix: movable-area 的@scale 回调有误

src/platforms/app-plus-nvue/runtime/components/picker.js
=> add picker component

docs/component/barcode.md
=> 将文档中setFlash参数类型改为Boolean

docs/api/other/report.md
=> edit report.md

docs/api/ui/intersection-observer.md
=> fix: fix docs

docs/api/plugins/login.md
修复 uni.getUserInfo 中的 lang 字段类型错误
=> docs: update login.md

docs/collocation/pages.md
https://uniapp.dcloud.io/collocation/pages
=> 官网文档中 - globalStyle部分的内容中表格项非对齐

src/platforms/mp-weixin/runtime/wrapper/component-base-parser.js
mp-weixin平台下，让Component构造器中支持更多的options配置
=> 增强微信小程序Component构造器中options的配置，让其支持更多options配置，如styleIsolation

docs/uniCloud/resource.md
新增uniCloud微信发红包-企业付款到零钱，即知识点：uniCloud.httpclient携证书发起请求
=> 新增uniCloud微信发红包-企业付款到零钱

docs/collocation/package.md
=> 自定义条件编译基准平台中去除app-plus

docs/casecode.md
- [仿抖音短视频示例](https://ext.dcloud.net.cn/plugin?id=860)：基于uni-app的nvue编译的高性能原生项目 -- by 林举
=> 仿抖音滑动切换视频项目

docs/uniCloud/resource.md
=> 新增unipush……URL更正

docs/uniCloud/learning.md
因为腾讯课堂限制了，课程报名时间。导致现在新用户要看课程都报名不了。
现在已经将课程上传到网易云课堂；新链接：
https://study.163.com/course/introduction.htm?courseId=1209978085#/courseDetail?tab=1
请帮忙更换一下
=> 因为腾讯课堂限制了，课程报名时间。导致现在新用户要看课程都报名不了。

src/platforms/mp-baidu/runtime/wrapper/util.js
=> 修复百度小程序下mounted可能不执行的问题

docs/component/video.md
- 视频播放格式说明：去掉“H5平台：支持的视频格式视浏览器而定”多余“支持”文字
=> 去掉多余‘支持’文字

docs/component/video.md
https://img.cdn.aliyun.dcloud.net.cn/guide/uniapp/%E7%AC%AC1%E8%AE%B2%EF%BC%88uni-app%E4%BA%A7%E5%93%81%E4%BB%8B%E7%BB%8D%EF%BC%89-%20DCloud%E5%AE%98%E6%96%B9%E8%A7%86%E9%A2%91%E6%95%99%E7%A8%8B@20200317.mp4
=> video url change

src/platforms/mp-alipay/runtime/wrapper/page-parser.js, src/platforms/mp-alipay/runtime/wrapper/util.js
=> fix no triggerEvent() function when invoke this.$emit() in page.

packages/uni-cli-shared/lib/plugin.js
=> perf:initExtends条件优化

docs/component/video.md
=> docs: 更换video文档同层播放器x5文档链接地址

docs/uniCloud/clientdb.md
=> 修改update下面解释说明错误

docs/component/video.md
完善了video组件 playStrategy、codec  字段描述
=> update video  playStrategy、codec  desc.

docs/component/map.md
=> docs: map 组件添加 @poitap 事件文档

src/platforms/app-plus/service/api/network/request.js
使用 uni.request 过程中，如果url 响应的Set-Cookie返回 ： “a=123; expires=Sun, 30-Oct-22 06:31:45 GMT; ”
解析到数组的时候，会解析成两个item。
=> Fix:cookie sometime parse error and typo

docs/api/ui/tabbar.md
=> docs: fix typo in tabbar.md

docs/uniCloud/unicloud-db.md
=> doc: Update unicloud-db.md

docs/vue-components.md
与 vue 文档对齐，使读者更易理解 prop 作为初始值时，变更 prop 的情形。
=> doc: update vue-components.md

docs/collocation/pages.md
=> docs: fix typo in pages.md

packages/uni-mp-alipay/dist/index.js, src/platforms/mp-weixin/runtime/wrapper/app-base-parser.js
文档地址：https://opendocs.alipay.com/mini/framework/app-detail
=> feat(mp-alipay): 支付宝小程序全局分享设置

packages/uni-components/src/helpers/hidpi.js
=> fix: 解决 H5 端 canvas 无法绘制文字的 bug

packages/uni-h5/src/service/api/route/switchTab.ts
=> fix: 解决 H5 下拉刷新的 bug

packages/uni-mp-kuaishou/lib/uni.config.js
=> feat(subpackages): add kuaishou support.

packages/uni-mp-baidu/src/compiler/options.ts
=> fix(uni-mp-baidu): support baidu talos components

packages/uni-mp-xhs/dist/index.js, src/platforms/mp-xhs/runtime/wrapper/page-parser.js
fix the issue of useRef component being undefined in xhs
=> fix(uni-mp-xhs): fix vue2 the issue of useRef component being undefined

src/platforms/mp-toutiao/runtime/wrapper/util.js
=> fix(mp-toutiao): refs invalid in TikTok App 27.2.0

packages/shims-uni-app.d.ts, packages/uni-h5-vite/src/plugins/manifestJson.ts, packages/uni-h5-vite/src/plugins/pagesJson.ts, packages/uni-h5/dist/uni-h5.cjs.js, packages/uni-h5/dist/uni-h5.es.js, packages/uni-h5/src/helpers/location.ts, packages/uni-h5/src/view/components/map/MapCircle.tsx, packages/uni-h5/src/view/components/map/MapMarker.tsx, packages/uni-h5/src/view/components/map/MapPolyline.tsx, packages/uni-h5/src/view/components/map/index.tsx, packages/uni-h5/src/view/components/map/map-polygon/index.tsx, packages/uni-h5/src/view/components/map/maps/Callout.ts, packages/uni-h5/src/view/components/map/maps/bmapgl/bmapgl.base.d.ts, packages/uni-h5/src/view/components/map/maps/bmapgl/bmapgl.control.d.ts, packages/uni-h5/src/view/components/map/maps/bmapgl/bmapgl.core.d.ts, packages/uni-h5/src/view/components/map/maps/bmapgl/bmapgl.maplayer.d.ts, packages/uni-h5/src/view/components/map/maps/bmapgl/bmapgl.maptype.d.ts, packages/uni-h5/src/view/components/map/maps/bmapgl/bmapgl.overlay.d.ts, packages/uni-h5/src/view/components/map/maps/bmapgl/bmapgl.service.d.ts, packages/uni-h5/src/view/components/map/maps/bmapgl/index.d.ts, packages/uni-h5/src/view/components/map/maps/bmapgl/types.d.ts, packages/uni-h5/src/view/components/map/maps/index.ts, pnpm-lock.yaml
=> add bmapgl for h5 

packages/uni-mp-toutiao/src/compiler/options.ts
fix #4624 
fix #4627 
vue2 MR #4625
=> feat: support toutiao rtc-room

packages/uni-h5/dist-x/uni-h5.es.js, packages/uni-h5/dist/uni-h5.es.js, packages/uni-h5/src/service/api/device/network.ts
针对 h5 环境增加兼容代码，保证 h5 显示正常，已自测。
=> fix(h5): network status

packages/uni-app-plus/src/x/api/index.ts, packages/uni-app-plus/src/x/api/tabBar/hideTabBar.ts, packages/uni-app-plus/src/x/api/tabBar/hideTabBarRedDot.ts, packages/uni-app-plus/src/x/api/tabBar/onTabBarMidButtonTap.ts, packages/uni-app-plus/src/x/api/tabBar/removeTabBarBadge.ts, packages/uni-app-plus/src/x/api/tabBar/setTabBarBadge.ts, packages/uni-app-plus/src/x/api/tabBar/setTabBarItem.ts, packages/uni-app-plus/src/x/api/tabBar/setTabBarStyle.ts, packages/uni-app-plus/src/x/api/tabBar/showTabBar.ts, packages/uni-app-plus/src/x/api/tabBar/showTabBarRedDot.ts
=> feat(x): ios 实现 tabBar 相关 api

packages/uni-mp-weixin/dist/index.js, packages/uni-template-compiler/__tests__/compiler-mp-alipay.spec.js, packages/uni-template-compiler/__tests__/compiler-mp-baidu.spec.js, packages/uni-template-compiler/__tests__/compiler-mp-kuaishou.spec.js, packages/uni-template-compiler/__tests__/compiler-mp-lark.spec.js, packages/uni-template-compiler/__tests__/compiler-mp-qq.spec.js, packages/uni-template-compiler/__tests__/compiler-mp-toutiao.spec.js, packages/uni-template-compiler/__tests__/compiler-mp-weixin.spec.js, packages/uni-template-compiler/__tests__/compiler.spec.js, packages/uni-template-compiler/lib/auto-components.js, packages/uni-template-compiler/lib/h5.js, packages/uni-template-compiler/lib/index.js, packages/uni-template-compiler/lib/mp.js, packages/uni-template-compiler/lib/script/traverse/visitor.js, packages/uni-template-compiler/lib/template/traverse.js, packages/uni-template-compiler/lib/util.js
=> feat: add component whiteList and span of mp_weixin

packages/uni-app-vue/lib/uvue.runtime.esm.js
关联
https://github.com/fxy060608/vue-next/pull/77
=> feat(x): 同步 app-x 产物

packages/uni-app-vue/lib/uvue.runtime.esm.js
=> chore(x): 同步 uvue

packages/uni-mp-alipay/src/runtime/createComponent.ts
vue2 #4887
https://ask.dcloud.net.cn/question/190681
=> feat(mp-alipay): 支付宝小程序支持用户传递 options

packages/uni-components/__tests__/useField.spec.ts, packages/uni-components/src/helpers/useField.ts
相关自动化测试，涉及 input/textarea 两个组件
https://gitcode.net/dcloud/hello-uni-app-x/-/commit/de40580cee832b261aee167210196f4e4caa1ae3
=> fix(x-web): 正确处理未设置 modelValue和 value 的情况

packages/uni-app-vue/lib/uvue.runtime.esm.js, packages/uni-shared/src/lifecycle.ts
关联 vuejs 调整
https://github.com/fxy060608/vue-next/pull/80
解决 hello-uvue 自动化测试错误
=> feat(x): 调整 onShow 生命周期触发判断规则

packages/uni-app-plus/src/x/components/checkbox-group/model.ts, packages/uni-app-plus/src/x/components/checkbox/checkbox.tsx, packages/uni-app-plus/src/x/components/checkbox/model.ts, packages/uni-app-plus/src/x/components/navigator/model.ts, packages/uni-app-plus/src/x/components/picker-view/model.ts, packages/uni-app-plus/src/x/components/progress/model.ts, packages/uni-app-plus/src/x/components/radio-group/model.ts, packages/uni-app-plus/src/x/components/radio/model.ts
=> feat(x): iOS 内置组件重写 tagName/nodeName

packages/uni-app-plus/src/x/framework/app/tabBar.ts, packages/uni-app-plus/src/x/framework/theme.ts
refactor(x): iOS 暗黑模式替换变量的逻辑统一为对象操作
=> refactor(x): iOS 暗黑模式替换变量的逻辑统一为对象操作

packages/shims-uni-app.d.ts, packages/uni-app-plus/__tests__/x/framework/app/tabBar.spec.ts, packages/uni-app-plus/src/x/api/tabBar/setTabBarStyle.ts, packages/uni-app-plus/src/x/framework/app/tabBar.ts, packages/uni-app-plus/src/x/framework/theme.ts, packages/uni-h5/src/framework/components/layout/tabBar.tsx, packages/uni-h5/src/service/api/ui/tabBar.ts
borderColor 优先级高于 borderStyle
uni.setTabBarStyle 支持 borderColor
pages.json 支持 borderColor
=> feat(x): iOS 新增 tabBarBorderColor 选项

packages/uni-components/src/vue/input/index.tsx
ask社区：https://ask.dcloud.net.cn/question/194772?notification_id=1425224
=> fix(h5): 修复input中传入值为null时直接报错的bug question/194772

packages/uni-components/src/vue/input/index.tsx
=> fix: input type 渲染优化

packages/vue-cli-plugin-uni/lib/app-plus/getUrl.js
feat: isAbsoluteFile 变量调整， [相关ask](https://ask.dcloud.net.cn/question/194534)
=> feat: isAbsoluteFile 变量调整

packages/uni-cli-shared/src/json/mp/jsonFile.ts
feat: findUsingComponentsJson兼容test case
=> feat: findUsingComponentsJson兼容test case

src/core/helpers/interceptor.js
=> feat: 优化promise化

packages/uni-h5/src/framework/plugin/index.ts, packages/uni-h5/src/service/api/route/utils.ts
=> feat: 单页面跳转路由警告提示

packages/uni-components/src/vue/input/index.tsx
fix(app): input延迟执行digitdelete判断
fix: 修复input type 逻辑
=> fix(app): input 逻辑优化

packages/uni-app-plus/src/view/framework/dom/components/UniComponent.ts, packages/uni-components/src/vue/swiper/index.tsx
fix(app): swiper组件动态渲染修复 [ask: 175252](https://ask.dcloud.net.cn/question/175252)
=> Fix swiper

packages/shims-uni-app.d.ts, packages/uni-components/lib/page-meta/page-meta.vue, packages/uni-core/src/view/init/rem.ts, packages/uni-h5/src/framework/setup/page.ts, packages/uni-h5/src/service/api/ui/setPageMeta.ts
修复页面page-meta的root-font-size和pageStyle样式  相关issue https://github.com/dcloudio/uni-app/issues/5088
=> Fix page meta

packages/uni-cli-shared/src/vite/plugins/vitejs/plugins/asset.ts
fix: 补充静态资源base64缓存 相关issue https://github.com/dcloudio/uni-app/issues/5089
=> fix: 补充静态资源base64缓存

packages/uni-h5/src/service/api/base/canIUse.ts
=> fix(web): 修复canIUse总是返回true的问题

packages/uni-api/src/helpers/api/promise.ts, packages/uni-mp-core/src/api/promise.ts
=> fix(web): showToast和showLoading不修改传入的参数

packages/uni-h5/src/view/components/web-view/index.tsx
=> feat(h5): web-view组件支持load事件

packages/uni-h5/src/view/components/web-view/index.tsx
=> fix(web): webview添加缺失的src参数

src/platforms/h5/view/components/web-view/index.vue
=> feat(web): web-view组件支持load事件

packages/uni-mp-toutiao/src/compiler/options.ts
[https://ask.dcloud.net.cn/question/208940?item_id=297891&rf=false](https://ask.dcloud.net.cn/question/208940?item_id=297891&rf=false)
=> fix(mp-toutiao): 修复抖音留资组件绑定 order-id 属性编译异常问题 (question/297891)

packages/uni-h5/src/view/components/web-view/index-x.tsx
=> feat(x-web): web-view组件支持load事件

packages/uni-components/src/vue/progress/index.tsx
=> feat(web): progress 组件支持 strokeWidth 设置为rpx

packages/uni-h5-vite/src/plugins/ssr.ts
[https://ask.dcloud.net.cn/question/209401](https://ask.dcloud.net.cn/question/209401)
=> fix(web): 修复 ssr 模式下 vuex 路径解析失败的bug (question/209401)

packages/uni-mp-xhs/src/compiler/options.ts
[https://ask.dcloud.net.cn/question/209459?item_id=298584&rf=false](https://ask.dcloud.net.cn/question/209459?item_id=298584&rf=false)
=> fix(mp-xhs): 修复群聊组件属性编译异常的bug (question/209458)

packages/uni-app-harmony/src/service/api/context/operateWebView.ts, packages/uni-app-harmony/src/view/components/web-view/index.tsx
canBack、canForward、loadData、getPageHeight、clear
=> feat(harmony): createWebviewContext增加部分方法的支持

packages/uni-mp-alipay/__tests__/component.spec.ts, packages/uni-mp-alipay/src/compiler/options.ts
[https://ask.dcloud.net.cn/question/209649](https://ask.dcloud.net.cn/question/209649)
=> fix(mp-alipay): 修复 mpaas-component 组件编译后属性丢失的bug (question/209649)

src/core/view/bridge/subscribe/api/request-component-observer.js
[https://ask.dcloud.net.cn/question/209795](https://ask.dcloud.net.cn/question/209795)
=> fix: 修复 createIntersectionObserver 无法监听组件根节点的bug (question/209795)

packages/uni-mp-kuaishou/lib/uni.config.js, packages/uni-mp-xhs/lib/uni.config.js
[https://ask.dcloud.net.cn/question/210277](https://ask.dcloud.net.cn/question/210277)
[快手小程序项目私有配置官方文档](https://open.kuaishou.com/docs/develop/developerTools/Localization-project.html)
=> feat(mp): 快手，小红书小程序支持拷贝指定文件 (question/210277)

packages/uni-mp-alipay/__tests__/component.spec.ts, packages/uni-mp-alipay/src/compiler/options.ts
[share-element 共享元素
](https://opendocs.alipay.com/mini/04y2ya?pathHash=a4fa18ca)
[root-portal 容器](https://opendocs.alipay.com/mini/05snwp?pathHash=bccb8999)
=> feat(mp-alipay): 支持 root-portal 和 share-element 组件

src/platforms/mp-alipay/runtime/api/protocols.js
[https://ask.dcloud.net.cn/question/210415](https://ask.dcloud.net.cn/question/210415)
=> feat(mp-alipay): vue2 中 showModal 优先使用原生支持的实现 (question/210415)

packages/uni-template-compiler/__tests__/compiler.spec.js, packages/uni-template-compiler/lib/template/traverse.js
[https://ask.dcloud.net.cn/question/210780](https://ask.dcloud.net.cn/question/210780)
=> fix(mp): 修复 vue2 slot name为数字时运行报错的bug (question/210780)

packages/uni-app/src/apiLifecycle.ts, packages/uni-mp-vite/src/plugins/runtimeHooks.ts, packages/uni-shared/src/lifecycle.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix(mp-xhs): 修复 组合式 API 不能引入 onShareChat 的 Bug

packages/uni-mp-alipay/src/api/protocols.ts
[https://ask.dcloud.net.cn/question/211717?item_id=302267&rf=false](https://ask.dcloud.net.cn/question/211717?item_id=302267&rf=false)
=> fix(mp-alipay): API pageScrollTo 支持 duration 参数 (question/211717)

packages/vite-plugin-uni/src/cli/utils.ts
[https://ask.dcloud.net.cn/question/212420](https://ask.dcloud.net.cn/question/212420)
=> fix(cli): 补充遗漏的 mp-jd 和 mp-harmony 平台提示 (question/212420)

packages/uni-mp-vite/src/plugin/build.ts, packages/uni-mp-vite/src/plugins/entry.ts
close #5026 
[https://ask.dcloud.net.cn/question/185955](https://ask.dcloud.net.cn/question/185955)
=> perf(mp): 将子包依赖的 node_modules 内容打包到子包 vendor.js 中

packages/uni-mp-xhs/src/api/protocols.ts
小红书官方文档 [https://miniapp.xiaohongshu.com/doc/DC034783](https://miniapp.xiaohongshu.com/doc/DC034783)
=> fix(mp-xhs): rename requestOrderPayment to requestGuaranteeOrderPayment

src/platforms/mp-xhs/runtime/wrapper/util.js
=> refactor(mp-xhs): remove useless isComponent2 export
